#this will build a java project with maven
name: Continuous Integration
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest	
    name: Build with Java on ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Cache m2 folder
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: m2-${{hashFiles('**/pom.xml', '**/*.yaml')}}
        restore-keys: m2-
    - name: Build with Maven
      run: >
        xvfb-run mvn verify 